[package]
name = "hello_world"
version = "0.1.0"
authors = ["Strongly Typed"]
edition = "2018"

[dependencies]
time = "0.1.12"
regex = "0.1.41"
reqwest = { version = "0.10.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
select = "0.5.0"